###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID ee27)
#  Generated on:      Sat May 25 21:21:00 2024
#  Design:            CHIP
#  Command:           routeDesign -globalDetail -viaOpt -wireOpt
###############################################################
current_design CHIP
create_clock [get_ports {clk}]  -name clk -period 7.000000 -waveform {0.000000 3.500000}
set_propagated_clock  [get_ports {clk}]
set_drive 0.1  [get_ports {clk}]
set_drive 0.1  [get_ports {rst_n}]
set_drive 0.1  [get_ports {in_valid}]
set_drive 0.1  [get_ports {in_valid2}]
set_drive 0.1  [get_ports {mode}]
set_drive 0.1  [get_ports {matrix[7]}]
set_drive 0.1  [get_ports {matrix[6]}]
set_drive 0.1  [get_ports {matrix[5]}]
set_drive 0.1  [get_ports {matrix[4]}]
set_drive 0.1  [get_ports {matrix[3]}]
set_drive 0.1  [get_ports {matrix[2]}]
set_drive 0.1  [get_ports {matrix[1]}]
set_drive 0.1  [get_ports {matrix[0]}]
set_drive 0.1  [get_ports {matrix_idx[3]}]
set_drive 0.1  [get_ports {matrix_idx[2]}]
set_drive 0.1  [get_ports {matrix_idx[1]}]
set_drive 0.1  [get_ports {matrix_idx[0]}]
set_drive 0.1  [get_ports {matrix_size[1]}]
set_drive 0.1  [get_ports {matrix_size[0]}]
set_load -pin_load -max  20  [get_ports {out_valid}]
set_load -pin_load -min  20  [get_ports {out_valid}]
set_load -pin_load -max  20  [get_ports {out_value}]
set_load -pin_load -min  20  [get_ports {out_value}]
